### ISSUE TITLE
Query of historic rates recently stopped working - possibly due to changes made to the underlying service

### ISSUE THREAD

**Issue by TimMonks** [helloserve/ExchangeRatesApiClient#1]
Thanks for publishing this, it was working fine for me as a nuget package, however suddenly stopped working a few days ago. 
It seems https://exchangeratesapi.io/ now require an API key and that requesting historic data now requires a paid plan.

**Comment by helloserve** [comment]
Thanks for bringing this to my attention. It's been a few weeks since I've started up my other side project which uses this package.
My tests indicate that historic calls do work when you subscribe for a free API key.

**Comment by TimMonks** [comment]
Thanks Henk, do you plan to update the nuget package or should I work off the source?

**Comment by helloserve** [comment]
Yes absolutely. While the PR is open I would first want to test the changes from source against my usecase (side)project. Will merge and publish thereafter.

**Comment by helloserve** [comment]
Re-opening this because there appears to have been a few changes to the API itself as well, and the error reporting is now different too.

**Comment by TimMonks** [comment]
In the nuget package 1.1, whether I use getLatestRates or GetRatesForDate in code like the following then rate.Rates is null. 
```
                ExchangeRatesApiOptions options = new ExchangeRatesApiOptions();
                options.ApiUrl = "http://api.exchangeratesapi.io/v1/";
                options.ApiKey = "<my api key>";

                var rate = exchangeRateApiClient.GetLatestRates(
                    "GBP",
                    currencies.ToArray());
```

If I build the appropriate URL e.g. like the following ,with the same currencies, then it works fine. 
`http://api.exchangeratesapi.io/v1/2013-12-24?access_key=<my api key>&symbols=USD,CAD,JPY
`
Is there a method to retrieve error information or do you have suggestions?

Thanks

**Comment by helloserve** [comment]
They changed the error reporting. Every request is now a 200 OK, with a result structure which I have to interrogate using error codes. The Nuget package has no way at the moment to report an error or generate an exception - it relies on WebException at the moment to pass along to the consumer. You are seeing nulls because all requests are "successful".

As a side-note: only `/latest` seems to still be in place. `/history` has changed and instead it appears you can get history for only a single date on the free tier e.g. `/history/2020-05-06` (not as a query string). They introduced a `/timeseries` resource which is blocked on the free-tier, which still takes the `start_at` and `end_at` query params.

I guess this is ExchangeRateApi version 2.0, really. I will version the Nuget package accordingly when the updates are complete.
